SCREEN_WIDTH = 800
SCREEN_HEIGHT = 600
FPS = 60
PADDLE_WIDTH = 15
PADDLE_HEIGHT = 100
BALL_SIZE = 20
PADDLE_SPEED = 5
BALL_SPEED_X = 5
BALL_SPEED_Y = 5
GAME_TITLE = "Ping Pong Game"
WINNING_SCORE = 5
FONT_SIZE = 32
POWERUP_SIZE = 20
POWERUP_SPAWN_CHANCE = 0.01  # 1% chance to spawn a powerup each frame
POWERUP_TYPES = ["speed", "size", "ball_speed", "reverse", "shrink", "extra_life"]
PLAYER_LIVES = 3  # Number of lives each player starts with
